// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqftQCvdGlkv3anEBJKXYxwNihida-sI8',
    appId: '1:480918514503:web:3847961fcd811115453a62',
    messagingSenderId: '480918514503',
    projectId: 'st-square',
    authDomain: 'st-square.firebaseapp.com',
    storageBucket: 'st-square.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypkBD_iAJ-IXl_QCEoTcj8_BZ-kZUVAw',
    appId: '1:480918514503:android:4048b45d42ccf91b453a62',
    messagingSenderId: '480918514503',
    projectId: 'st-square',
    storageBucket: 'st-square.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVjdOMe2_nLnLkdo86pnl8sC_EiLemWk',
    appId: '1:480918514503:ios:61f2af155914ac93453a62',
    messagingSenderId: '480918514503',
    projectId: 'st-square',
    storageBucket: 'st-square.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVjdOMe2_nLnLkdo86pnl8sC_EiLemWk',
    appId: '1:480918514503:ios:61f2af155914ac93453a62',
    messagingSenderId: '480918514503',
    projectId: 'st-square',
    storageBucket: 'st-square.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqftQCvdGlkv3anEBJKXYxwNihida-sI8',
    appId: '1:480918514503:web:d013ee505548ac68453a62',
    messagingSenderId: '480918514503',
    projectId: 'st-square',
    authDomain: 'st-square.firebaseapp.com',
    storageBucket: 'st-square.firebasestorage.app',
  );
}
